### ISSUE TITLE
"Errno::ETXTBSY: Text file busy @ unlink_internal" Migrating from fog

### ISSUE THREAD

**Issue by testa19** [sorentwo/carrierwave-aws#101] opened 2017-01-24 11:45 UTC
Hi there,

Migrating from working fog:
After changing fog settings to carrierwave-aws i get an error
> Errno::ETXTBSY: Text file busy @ unlink_internal - /my_app/public/uploads/tmp/1485255514-19755-0001-4463/sitemap.xml.gz

carrierwave.rb
```
config.aws_credentials = {
    region: "eu-west-1",                        
    :access_key_id      => ENV["AWS_ACCESS_KEY"],                       
    :secret_access_key  => ENV["AWS_SECRET_KEY"]                         
  }
  config.aws_bucket  = ENV["AWS_BUCKET"]                     
  config.storage = :aws
```

`storage :aws` in all upploaders and:
```
  def store_dir
    "uploads/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
  end

  def root
    Rails.root.join 'public/'
  end
```

In sitemap.rb (Sitemap_generator):
```
SitemapGenerator::Sitemap.default_host = "http://www.myapp.com/"
SitemapGenerator::Sitemap.sitemaps_host = "http://mayapp.s3.amazonaws.com/"
SitemapGenerator::Sitemap.public_path = 'tmp/'
SitemapGenerator::Sitemap.sitemaps_path = 'sitemaps/'

SitemapGenerator::Sitemap.adapter = SitemapGenerator::WaveAdapter.new(provider: 'AWS',access_key_id: ENV["AWS_ACCESS_KEY"],
                                         secret_access_key: ENV["AWS_SECRET_KEY"],
                                         aws_bucket: ENV["AWS_BUCKET"],
                                         region: "eu-west-1",
                                         permissions: 0666,
                                         storage: :aws)
```
>/usr/local/lib/ruby/2.3.0/fileutils.rb:1451:in `block in remove_file'
>  /usr/local/lib/ruby/2.3.0/fileutils.rb:1456:in `platform_support'
>  /usr/local/lib/ruby/2.3.0/fileutils.rb:1450:in `remove_file'
>  /usr/local/lib/ruby/2.3.0/fileutils.rb:794:in `remove_file'
>  /usr/local/lib/ruby/2.3.0/fileutils.rb:572:in `block in rm'
>  /usr/local/lib/ruby/2.3.0/fileutils.rb:571:in `rm'
>  carrierwave (1.0.0) lib/carrierwave/sanitized_file.rb:244:in `delete'
>  carrierwave (1.0.0) lib/carrierwave/uploader/store.rb:59:in `block in store!'
>  carrierwave (1.0.0) lib/carrierwave/uploader/callbacks.rb:15:in `with_callbacks'
>  carrierwave (1.0.0) lib/carrierwave/uploader/store.rb:56:in `store!'
>  carrierwave (1.0.0) lib/carrierwave/mounter.rb:100:in `store!'
>  carrierwave (1.0.0) lib/carrierwave/mount.rb:393:in `store_image!'
>  activesupport (5.0.1) lib/active_support/callbacks.rb:382:in `block in make_lambda'
>  activesupport (5.0.1) lib/active_support/callbacks.rb:207:in `block in halting_and_conditional'
>  activesupport (5.0.1) lib/active_support/callbacks.rb:456:in `block in call'
>  activesupport (5.0.1) lib/active_support/callbacks.rb:456:in `call'
>  activesupport (5.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
> activesupport (5.0.1) lib/active_support/callbacks.rb:750:in `_run_save_callbacks'
>  activerecord (5.0.1) lib/active_record/callbacks.rb:298:in `create_or_update'
>  activerecord (5.0.1) lib/active_record/persistence.rb:125:in `save'
>  activerecord (5.0.1) lib/active_record/validations.rb:44:in `save'
Thanks

**Comment by sorentwo** [comment] 2017-01-25 03:59
Does this happen consistently? Is it happening during a deployment? That particular error would only happen when there is interplay between two processes trying to either write/delete a file which is currently being executed, or executing a file which is currently open for writing.

I'm not familiar with SitemapGenerator, but a quick search shows that it also has `SitemapGenerator::AwsSdkAdapter`, which would use `aws-sdk`, the same AWS library this gem uses. I don't believe the issue is coming from `carrierwave-aws` though, so I'm going to close this.

**Closed by sorentwo** 2017-01-25 03:59 UTC

**Comment by testa19** [comment] 2017-01-25 17:16
It happens every time there is an upload (image or sitemap-file).
